### ISSUE TITLE
interesting-but flawed code

### ISSUE THREAD

**Issue by JazzMaster** [daar/GLPT#8]
there is a lot to cover- thats why I didnt specify much.
suggestions:

there is no exit(xyz)-
its: 

return(xyz) 

or 
functionName:=xyz.

Im seeing this in other places. Those people have used another library override of the LCL- and they redefine the language. You dont seem to be doing that. So either this is not wirtten for FPC- or its written assuming a flawed interpreter.

2ndly- travisCL doesnt support Pascal. Why you think it will is beyond me. Id love to use it for tracing sources- but it doesnt support Pascal.

You hand off the methods to the OS specific functions. nothing wrong there. 

But using GDI and X11 core is where you go wrong. 

Further it seems the GL code references the old xgl libs, not the newer GL ones. 
This could be the problem.

GL,GLU, Glext-

and you are rewriting GLUT/freeGLUT. Theres no need to do that.

GL is either available- 
post XP, 
with X11, 
installed alongside Carbon- or its not.

Cocoa- OS9- isnt supported. 
(You need DirectDraw calls for that OS.)
minimum supported OpenGL is for OSX 10.2.

There is no need to avoid GL calls. 
win32 and Carbon parts of the API are avoiding GL calls.

x11 uses them- but only if we hook X11 functions(like the GDI) 
- which is not the proper way to do things.

GL and GLU/GLUT/freeGLUT can handle window contexts for you.

Unless you are giving us threaded input- and otherwise giving us functions that GLUT isnt providing- there is no need to avoid it.

While most prefer SDL syntax for input processing- it too has a "you cannot process input while rendering in a loop" bug. freeGLUT has the same issue. I doubt youve fixed this.

seems to me like may know SDL- 
(and its a good start) but you may not know the "GL basics".

Id like to see this go further.

**Comment by daar** [comment]
Lot's of questions and remarks. I will answer them in a number of comments;

As for exit(xyz). It's perfectly fine to use it in either FPC or Delphi. It's just a shorter notation, hence it is used.

- https://www.freepascal.org/docs-html/rtl/system/exit.html
- http://docs.embarcadero.com/products/rad_studio/delphiAndcpp2009/HelpUpdate2/EN/html/delphivclwin32/System_Exit.html

**Comment by daar** [comment]
You are correct about TravisCI not supporting Pascal out of the box. However, if you click on the TravisCI button in the README.md or follow this link: https://travis-ci.org/daar/GLPT, you will see that it works. There is an issue with Windows, but as soon as I will find the time, it will be resolved and we can test all 3 platforms via TravisCI.

In short the machine that executes the TravisCI script allows you to install and execute custom packages. I just use this principle to install FPC and then compile. On Windows (a service which was released just recently), there is an issue with finding compiled units by the FPC compiler.

**Comment by daar** [comment]
> You hand off the methods to the OS specific functions. nothing wrong there.
> But using GDI and X11 core is where you go wrong.

Why so? GLPT is meant to be a Pascal native replacement of GLUT and GLFW to name a few. The idea of that is to lose the dependency on external libraries. Using GDI or X11 is where one ends up in that case.

**Comment by daar** [comment]
> Further it seems the GL code references the old xgl libs, not the newer GL ones.
> This could be the problem.

I'm not convinced yet there IS a problem. The use of the GLX unit for X11 is only for utilizing the `glXCreateContext` function. Possibly this will be replaced by a native X11 call in the future.

Making a reference to GL is soly the responsibility of the end user. GLPT is only a toolkit that provides a native context. Nothing more.

**Comment by daar** [comment]
> Unless you are giving us threaded input- and otherwise giving us functions that GLUT isnt providing- there is no need to avoid it.

True, but I want to!

> While most prefer SDL syntax for input processing- it too has a "you cannot process input while rendering in a loop" bug. freeGLUT has the same issue. I doubt youve fixed this.

That is the nice thing about making a Pascal native library. **WE** can fix it!

> seems to me like may know SDL-
> (and its a good start) but you may not know the "GL basics".
> Id like to see this go further.

Me too. I'm accepting pull requests for new and exciting additions to GLPT!

TIA

**Comment by genericptr** [comment]
> and you are rewriting GLUT/freeGLUT. Theres no need to do that.
> 
> GL is either available-
> post XP,
> with X11,
> installed alongside Carbon- or its not.
> 
> Cocoa- OS9- isnt supported.
> (You need DirectDraw calls for that OS.)
> minimum supported OpenGL is for OSX 10.2.
> 
> There is no need to avoid GL calls.
> win32 and Carbon parts of the API are avoiding GL calls.

I really don't understand what you're saying here because it's so vague. How are we avoiding GL calls? What do you mean about GLUT? The point of the project is so we have a native Pascal API that doesn't rely on external libraries and ancient things like GLUT.
