### ISSUE TITLE
GLPT_Context Question

### ISSUE THREAD

**Issue by davidbruce** [daar/GLPT#9]
What is the GLPT_Context used for?

https://github.com/daar/GLPT/blob/a6d0e57d0dc7c05ab18840508ce53413bba6f954/GLPT.pas#L619-L627

Is the majorVersion and minorVersion supposed to control what OpenGL version is loaded?
It doesn't look like any of these properties are used in any platform specific code when generating the actual OpenGL context. 

For example X11 just sets dpy and passes that around.  
https://github.com/daar/GLPT/blob/a6d0e57d0dc7c05ab18840508ce53413bba6f954/GLPT_X11.inc#L332

I attempted to create my own Context and pass it to GLPT_CreateWindow, but it didn't seem to load any opengl versions based on what I set majorVersion or minorVersion.

I ended up having to do the following otherwise anything from GLExt (e.g. glCreateShader) appears to throw an Access Violation error:
``` 
    if not GLPT_Init then halt(-1);

    window := GLPT_CreateWindow(0, 0, width, height, 'Hello Triangle', GLPT_GetDefaultContext);
    if window = nil then
    begin
        GLPT_Terminate();
        halt(-1);
    end;

    window^.event_callback := @event_callback;

    //this check appears to be needed?
    if Load_GL_VERSION_3_3 = false then
    begin
        writeln(' ERROR: OpenGL 3.3 is needed. '); 
        GLPT_Terminate();
        halt(-1);
    end;
```

Is what I'm doing how you intend it to work?

**Comment by genericptr** [comment]
GLPT isn't implemented fully in all areas right now so the context may only work for MacOS (the portion that I'm responsible for).

**Comment by davidbruce** [comment]
Gotcha, thanks for getting back to me and I'm sorry about the late response!
